export interface IMovieDetails {
  title: string,
  description: string,
  actors: string,
  poster: string,
  imdbRating: string,
  year?: string,
  released?: string,
  runtime?: string,
  genre?: string,
  director?: string,
  writer?: string,
  language?: string,
  country?: string,
  awards?: string,
  metascore?: string,
  imdbVotes?: string,
  type?: string,
  Response?: string,
}